### ISSUE TITLE
Question about implemetation of eq.1

### ISSUE THREAD

**Issue by Mistariano** [ajhamdi/ges-splatting#3]
Hi guys,

thanks a lot for your efforts. I notice that in eq.(1) of the arxiv paper, beta is a learnable parameter, but in the current implementation, it is still fixed to 2:
https://github.com/ajhamdi/ges-splatting/blob/ea4f2df113d35db2c76a448dd1101c402348eef3/submodules/diff-gaussian-rasterization/cuda_rasterizer/forward.cu#L335

Seems like even when we are using non-Gaussian kernels (i.e. `render_laplacian`), we are still drawing Gaussians with covariance matrices linearly scaled by Phi(beta), as described in eq.(4).

Is it true that the rasterizer implementation isn't updated? Or maybe I miss something and misunderstand it.

**Comment by ajhamdi** [comment]
no, you understood correctly, we use the same rasterizer as Gaussian Splatting, but different splatting features during the optimization. Specifically, we modify the scales based on the learned shape parameters such that the projected variance of each component will be AS IF we did take the exponent. It is an approximation that introduces some error we quantify in  Section B.1 in the paper Appendix. 

I hope this helped

**Comment by AuroraRyan0301** [comment]
> no, you understood correctly, we use the same rasterizer as Gaussian Splatting, but different splatting features during the optimization. Specifically, we modify the scales based on the learned shape parameters such that the projected variance of each component will be AS IF we did take the exponent. It is an approximation that introduces some error we quantify in Section B.1 in the paper Appendix.
> 
> I hope this helped

Hi，I also noticed this trick for implementation. However, I cannot be persuaded by the trick for the following reasons:

1. It seems quite easy and intuitive to directly modify the CUDA kernel function. I mean that someone can add an addtional parameter beta, and change G=exp(-power) to exp(-exp(beta* ln(|power|))). Of course, power also needs to be truncated near zero to avoid the instability in numerical calculation. And dG/dbeta will be exp(-exp(beta* ln(|power|))) * (-exp(beta* ln(|power|)) * ln(|power|.
So I wonder why not implementing generatized gaussian in CUDA kernel directly? Did you do any test on this kind of implementation?

2.  The learned shape parameters are view-independent. If I understand it right, it just removes the requirement of normalization for gauss distribution because it's just a linear scaling. It seems the essential of improvements is irrelevant to Generized Gaussian. Did you do any visualization for **single** 3D Generized Gaussian to show actual shapes from arbitary perspective?

Maybe I miss something and misunderstand it. I'd appreciate it if you could elaborate the trick. Thanks.

**Comment by SubhadraG** [comment]
> > no, you understood correctly, we use the same rasterizer as Gaussian Splatting, but different splatting features during the optimization. Specifically, we modify the scales based on the learned shape parameters such that the projected variance of each component will be AS IF we did take the exponent. It is an approximation that introduces some error we quantify in Section B.1 in the paper Appendix.
> > I hope this helped
> 
> Hi，I also noticed this trick for implementation. However, I cannot be persuaded by the trick for the following reasons:
> 
> 1. It seems quite easy and intuitive to directly modify the CUDA kernel function. I mean that someone can add an addtional parameter beta, and change G=exp(-power) to exp(-exp(beta* ln(|power|))). Of course, power also needs to be truncated near zero to avoid the instability in numerical calculation. And dG/dbeta will be exp(-exp(beta* ln(|power|))) * (-exp(beta* ln(|power|)) * ln(|power|.
>    So I wonder why not implementing generatized gaussian in CUDA kernel directly? Did you do any test on this kind of implementation?
> 2. The learned shape parameters are view-independent. If I understand it right, it just removes the requirement of normalization for gauss distribution because it's just a linear scaling. It seems the essential of improvements is irrelevant to Generized Gaussian. Did you do any visualization for **single** 3D Generized Gaussian to show actual shapes from arbitary perspective?
> 
> Maybe I miss something and misunderstand it. I'd appreciate it if you could elaborate the trick. Thanks.

+1. Other than the multiplication in this line https://github.com/ajhamdi/ges-splatting/blob/c05fc7dbb22e270a5a6f490e7040adac4af02c96/gaussian_renderer/__init__.py#L150 (which I believe is explained with eq. 4), what exactly is being modified in the codebase compared to the original Gaussian splatting? Would this just be equivalent to learning a different scaling value with the original GS algorithm?
